# Generated by Django 6.0.4 on 2026-05-02 02:20

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Marketplace', '0002_userprofile_alter_cart_user_alter_order_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cardNum',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
