# Generated by Django 6.0.4 on 2026-05-02 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Marketplace', '0003_alter_userprofile_cardnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
