# Generated by Django 6.0.4 on 2026-05-02 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Marketplace', '0004_product_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileImgLink',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
