# Generated by Django 6.0.4 on 2026-05-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Marketplace', '0005_alter_userprofile_profileimglink'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productimg',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
