# Generated by Django 6.0.4 on 2026-05-02 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Online_Marketplace', '0006_product_productimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productimg',
            field=models.ImageField(upload_to='product_images/'),
        ),
    ]
