services:
  - type: web
    name: online-marketplace-backend
    rootDir: Backend  
    buildCommand: "./build.sh"
    startCommand: "gunicorn Online_Marketplace.wsgi"

    envVars:
      - key: DEBUG
        value: False
