services:
    - type: web
    name: bayoustore
    env: python
    buildcommand: "./build.sh"
    startcommand: "gunicorn OnlineMarketplace.wsgi:application"
    envVars:
        -key: DEBUG
        value: False