services:
  - type: web
    name: bayoustore
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn Online_Marketplace.wsgi:application"

    envVars:
      - key: DEBUG
        value: False
